language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
- 3.6-dev
- 3.7-dev
- nightly
install:
- pip install -U pip
- if [[ $TRAVIS_PYTHON_VERSION == 2.6* ]]; then pip install --only-binary -e .; else pip install --prefer-binary -e .; fi
script: python setup.py test 
